
FROM ruby:3.2.2

WORKDIR /app

RUN apt update
RUN apt install -y postgresql-client firefox-esr npm
RUN gem install rspec capybara selenium-webdriver
RUN npm install -g nodemon

CMD [ "nodemon", "--ext", "rb,js,html,css", "--exec", "ruby", "server.rb" ]
