
version: '3'

services:
  postgres_db:
    image: postgres:16

    ports:
      - 5432:5432

    env_file: .env.postgres

    restart: always

    volumes:
      - ./sql_scripts/:/docker-entrypoint-initdb.d/

  api:
    build:
      context: ./src
      dockerfile: ../Dockerfile.api

    ports:
      - 10000:10000

    env_file: .env.api

    volumes:
      - ./src/:/app
      - ./sample/data.csv:/app/sample/data.csv
