
version: '3'

services:
  postgres_db:
    image: postgres:16

    ports:
      - 5432:5432

    env_file: .env.postgres

    restart: always

    volumes:
      - ./sql_scripts/:/docker-entrypoint-initdb.d/
      - ./.pg_data:/var/lib/postgresql/data

  api: &api
    build:
      context: ./src
      dockerfile: ../Dockerfile.api

    ports:
      - 10000:10000

    env_file: .env.api

    volumes:
      - ./src/:/app
      - ./sample/data.csv:/app/sample/data.csv

    depends_on:
      - postgres_db

  dev:
    <<: *api

    command: nodemon --ext rb,js,html,css --exec ruby server.rb
